name: Run Python script

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: python ./assets/model/main.py  # Replace with the actual path to your Python script
