name: Run Python script

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-script:
    runs-on: linux

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: python CryptoGig/assets/model/main.py
